### ISSUE TITLE
Is there any ETA on releasing v0.3?

### ISSUE THREAD

**Issue by s3rvac** [cloudera/python-sasl#25]
On 2021-04-14, [v0.3a1 was released](https://github.com/cloudera/python-sasl/releases/tag/v0.3a1). Is there any ETA on releasing v0.3? It contains the changes from #23, which we need to use this library from Python 3.9 (CC @enkelli).

**Comment by attilajeges** [comment]
Hi! I've just released v0.3: https://pypi.org/project/sasl/0.3/

**Comment by s3rvac** [comment]
Cool, thank you! :+1: :tada:
