### ISSUE TITLE
Difference with the PyPi python sasl package

### ISSUE THREAD

**Issue by garaud** [cloudera/python-sasl#3]
Hi,

I'm trying to work with the Apache thrift / Hive family with Python 3 and need to work with a SASL wrapper for Python. There is a sasl Pypi package at https://pypi.python.org/pypi/sasl which is related to this code source https://github.com/toddlipcon/python-sasl

What's the difference between yours and the "PyPi official" one? Is it related with this issue about Python 3 and cython at https://github.com/toddlipcon/python-sasl/issues/11

Is there a will to put this code on PyPi?

Thanks. Regards,
Damien G.

**Comment by wesm** [comment]
This is the code that is here: https://pypi.python.org/pypi/sasl

**Comment by garaud** [comment]
OK, thanks. I'll propose a tiny patch to update the `setup.py`.

It will be great if you can `git tag` the source code with the related PyPi version

**Comment by wesm** [comment]
Done

**Comment by torsava** [comment]
Could you also please update the "Home Page" link on PyPI? It's still pointing to the repo http://github.com/toddlipcon/python-sasl and not here.

**Comment by wesm** [comment]
Done
