### ISSUE TITLE
command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

### ISSUE THREAD

**Issue by enfeizhan** [cloudera/python-sasl#8]
I got this error on Ubuntu 16.04, miniconda3, python 2.7 or python 3.5:
``
building 'sasl.saslwrapper' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/sasl
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isasl -I/home/fei/miniconda3/envs/python3/include/python3.5m 
-c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-3.5/sasl/saslwrapper.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from sasl/saslwrapper.cpp:254:0:
    sasl/saslwrapper.h:22:23: fatal error: sasl/sasl.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
``
Hopefully the info here is enough to locate the bug.

**Comment by toddlipcon** [comment]
Sounds like you don't have the sasl development package installed (apt-get install libsasl2-dev)
